# Generated by Django 2.2.10 on 2020-05-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_commande_produit_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='tags',
        ),
        migrations.AddField(
            model_name='produit',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='compte.Tag'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('interieur', 'interieur'), ('exterieur', 'exterieur')], max_length=200),
        ),
    ]
