# Generated by Django 2.2.10 on 2020-05-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_commande_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en attente', 'en attente'), ('livrer', 'livrer'), ('commande total', 'commande total')], max_length=200, null=True),
        ),
    ]
