# Generated by Django 2.2.10 on 2020-05-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='myprofile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
