# Generated by Django 2.2.10 on 2020-05-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0008_auto_20200527_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix',
        ),
        migrations.AddField(
            model_name='commande',
            name='prix',
            field=models.FloatField(null=True),
        ),
    ]
