# Generated by Django 2.2.10 on 2020-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0009_auto_20200527_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nombre_produit',
            field=models.FloatField(null=True),
        ),
    ]
